sudo: required
services:
  - docker

before_install:
  - docker build -t iamuv2000/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true iamuv2000/react-test npm test

after_success:
  - docker build -t iamuv2000/multi-client ./client
  - docker build -t iamuv2000/multi-nginx  ./nginx 
  - docker build -t iamuv2000/multi-server ./server
  - docker build -t iamuv2000/multi-worker ./worker

  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push to docker hub
  - docker push iamuv2000/multi-client
  - docker push iamuv2000/multi-nginx
  - docker push iamuv2000/multi-server
  - docker push iamuv2000/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region : ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-502279622047
  bucket_path:  docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  






